# Generated by Django 5.1.15 on 2026-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('ACCEPTATION', 'Acceptation'), ('REJET', 'Rejet'), ('NOUVELLE_RECLAMATION', 'Nouvelle réclamation'), ('RAPPEL_RETARD', 'Rappel de retard'), ('INFORMATION', 'Information')], default='INFORMATION', max_length=30, verbose_name='Type de notification')),
                ('contenu', models.TextField(help_text='Message de la notification', verbose_name='Contenu')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('fcm_message_id', models.CharField(blank=True, help_text='Identifiant du message Firebase Cloud Messaging', max_length=255, verbose_name='ID message FCM')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
