# Generated by Django 5.1.15 on 2026-07-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='fcm_message_id',
        ),
    ]