# Generated by Django 5.1.15 on 2026-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('ARCHIVEE', 'Archivée')], max_length=20, verbose_name='Statut précédent')),
                ('nouveau_statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('ARCHIVEE', 'Archivée')], max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Historique des statuts',
                'verbose_name_plural': 'Historique des statuts',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(help_text='Pièce jointe (PDF, image)', upload_to='pieces_jointes/%Y/%m/', verbose_name='Fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('ERREUR_SAISIE', 'Erreur de saisie'), ('OUBLI_NOTE', 'Oubli de note'), ('VERIFICATION_COPIE', 'Demande de vérification de copie'), ('AUTRE', 'Autre motif')], max_length=30, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('ARCHIVEE', 'Archivée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la réclamation', verbose_name='Description')),
                ('commentaire_decision', models.TextField(blank=True, help_text="Commentaire obligatoire lors de l'acceptation/rejet", verbose_name='Commentaire de décision')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_limite_traitement', models.DateTimeField(verbose_name='Date limite de traitement')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('note_originale', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur de la note au moment de la réclamation', max_digits=5, null=True, verbose_name='Note originale')),
                ('nouvelle_note', models.DecimalField(blank=True, decimal_places=2, help_text='Nouvelle valeur si la note a été modifiée', max_digits=5, null=True, verbose_name='Nouvelle note')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
