# Generated by Django 5.1.15 on 2026-06-22 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0003_add_type_note'),
        ('reclamations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquestatut',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='coordonnateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='reclamations.reclamation', verbose_name='Réclamation'),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='reclamations.reclamation', verbose_name='Réclamation'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['statut'], name='reclamation_statut_60e392_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['etudiant', 'statut'], name='reclamation_etudian_2a0dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['date_limite_traitement'], name='reclamation_date_li_57c381_idx'),
        ),
    ]
