# Generated by Django 5.1.15 on 2026-06-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestatut',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('ARCHIVEE', 'Archivée')], max_length=20, null=True, verbose_name='Statut précédent'),
        ),
    ]
