# Generated by Django 5.1.15 on 2026-07-10 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_alter_historiquestatut_statut_precedent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='commentaire_professeur',
            field=models.TextField(blank=True, verbose_name='Commentaire du professeur'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='enseignant_assigne',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Professeur assigné'),
        ),
    ]
