# Generated by Django 5.1.15 on 2026-07-10 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_remove_old_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestatut',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='date_modification',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='nouveau_statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_REVISION_ENSEIGNANT', 'En révision par le professeur'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('ARCHIVEE', 'Archivée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='reclamations.reclamation'),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_REVISION_ENSEIGNANT', 'En révision par le professeur'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('ARCHIVEE', 'Archivée')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='fichier',
            field=models.FileField(upload_to='pieces_jointes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='nom_fichier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='reclamations.reclamation'),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='taille',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='commentaire_decision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='commentaire_professeur',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='coordonnateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_limite_traitement',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='enseignant_assigne',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_REVISION_ENSEIGNANT', 'En révision par le professeur'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('ARCHIVEE', 'Archivée')], default='EN_ATTENTE', max_length=30),
        ),
    ]
