# Generated by Django 5.1.15 on 2026-07-10 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0008_alter_historiquestatut_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereclamation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='reclamations.lignereclamation'),
        ),
    ]
