# Generated by Django 5.1.15 on 2026-07-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_hierarchical_structure'),
        ('reclamations', '0009_lignereclamation_description_piecejointe_ligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereclamation',
            name='type_note',
            field=models.CharField(choices=[('CONTINU', 'Continu (CC)'), ('FINAL', 'Final (Examen)')], default='CONTINU', help_text='Continu (CC) ou Final (Examen)', max_length=10, verbose_name='Type de note'),
        ),
        migrations.AlterUniqueTogether(
            name='lignereclamation',
            unique_together={('reclamation', 'element_module', 'type_note')},
        ),
    ]
