# Generated by Django 5.1.15 on 2026-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_hierarchical_structure'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='elements_enseignes',
            field=models.ManyToManyField(blank=True, help_text='Éléments que cet enseignant est autorisé à consulter', related_name='enseignants', to='notes.elementmodule', verbose_name='Éléments enseignés'),
        ),
    ]
