# Generated by Django 5.1.15 on 2026-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_hierarchical_structure'),
        ('users', '0002_alter_user_managers_user_modules_enseignes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modules_enseignes',
            field=models.ManyToManyField(blank=True, help_text='Modules que cet enseignant est autorisé à consulter', related_name='enseignants', to='notes.module', verbose_name='Modules enseignés'),
        ),
    ]
