# Generated by Django 5.1.15 on 2026-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_computed_fields'),
        ('users', '0002_alter_user_managers_user_modules_enseignes'),
    ]

    operations = [
    ]
