# Generated by Django 5.1.15 on 2026-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nouvelle valeur')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-date_modification'],
                'permissions': [('cannot_delete_auditlog', 'Cannot delete audit logs')],
            },
        ),
    ]
