# Generated by Django 5.1.15 on 2026-07-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
    ]
