# Generated by Django 5.1.15 on 2026-07-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_hierarchical_structure'),
        ('notes', '0004_hierarchical_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='element_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='notes.elementmodule', verbose_name='Élément concerné'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='type_note',
            field=models.CharField(choices=[('CONTINU', 'Continu (CC)'), ('FINAL', 'Final (Examen)')], default='CONTINU', help_text='Continu (CC) ou Final (Examen)', max_length=10, verbose_name='Type de note'),
        ),
    ]
