# Generated by Django 5.1.15 on 2026-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteElementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(help_text='Code unique du module (ex: INF-2024)', max_length=20, verbose_name='Code Module')),
                ('nom_module', models.CharField(blank=True, max_length=200, verbose_name='Nom du module')),
                ('semestre', models.CharField(help_text='Semestre concerné (ex: S1, S2)', max_length=20, verbose_name='Semestre')),
                ('annee_academique', models.CharField(help_text='Ex: 2024-2025', max_length=20, verbose_name='Année académique')),
                ('valeur_note', models.DecimalField(decimal_places=2, help_text='Note sur 20', max_digits=5, verbose_name='Note')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('est_verouillee', models.BooleanField(default=False, help_text='Si True, la note ne peut plus être modifiée', verbose_name='Note verrouillée')),
            ],
            options={
                'verbose_name': 'Note élémentaire',
                'verbose_name_plural': 'Notes élémentaires',
                'ordering': ['-annee_academique', 'code_module'],
            },
        ),
    ]
