# Generated by Django 5.1.15 on 2026-06-22 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noteelementaire',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='noteelementaire',
            unique_together={('etudiant', 'code_module', 'semestre', 'annee_academique')},
        ),
    ]
