# Generated by Django 5.1.15 on 2026-07-11 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_add_type_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(help_text='Code unique du module (ex: MIAG31)', max_length=20, verbose_name='Code Module')),
                ('nom_module', models.CharField(blank=True, max_length=200, verbose_name='Nom du module')),
                ('moy_module', models.DecimalField(decimal_places=2, help_text='Moyenne sur 20', max_digits=5, verbose_name='Moyenne du module')),
                ('note_finale', models.DecimalField(decimal_places=2, help_text='Note finale sur 20', max_digits=5, verbose_name='Note finale')),
                ('credit', models.DecimalField(decimal_places=2, help_text='Crédit du module', max_digits=4, verbose_name='Crédit')),
                ('observation', models.CharField(help_text='Validé ou Rattrapage', max_length=20, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['code_module'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='noteelementaire',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='noteelementaire',
            name='etudiant',
        ),
        migrations.CreateModel(
            name='ElementModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_element', models.CharField(help_text="Code unique de l'élément (ex: MIAG311)", max_length=20, verbose_name='Code Élément')),
                ('note_continu', models.DecimalField(decimal_places=2, help_text='Note de contrôle continu sur 20', max_digits=5, verbose_name='Note Continu (CC)')),
                ('note_final', models.DecimalField(decimal_places=2, help_text="Note d'examen sur 20", max_digits=5, verbose_name='Note Finale (Examen)')),
                ('note_moyenne', models.DecimalField(decimal_places=2, help_text="Moyenne de l'élément sur 20", max_digits=5, verbose_name='Note Moyenne')),
                ('credit', models.DecimalField(decimal_places=2, help_text="Crédit de l'élément", max_digits=4, verbose_name='Crédit')),
                ('observation', models.CharField(help_text='Validé ou Rattrapage', max_length=20, verbose_name='Observation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='notes.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Élément de module',
                'verbose_name_plural': 'Éléments de module',
                'ordering': ['code_element'],
            },
        ),
        migrations.CreateModel(
            name='ResultatSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moy_semestre', models.DecimalField(decimal_places=2, help_text='Moyenne générale sur 20', max_digits=5, verbose_name='Moyenne du semestre')),
                ('observation', models.CharField(help_text='Validé ou Rattrapage', max_length=20, verbose_name='Observation')),
                ('semestre', models.CharField(help_text='Semestre concerné (ex: S1, S2)', max_length=20, verbose_name='Semestre')),
                ('annee_academique', models.CharField(help_text='Ex: 2024-2025', max_length=20, verbose_name='Année académique')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_semestre', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Résultat de semestre',
                'verbose_name_plural': 'Résultats de semestres',
                'ordering': ['-annee_academique', 'semestre'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='resultat_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='notes.resultatsemestre', verbose_name='Résultat de semestre'),
        ),
    ]
