# Generated by Django 5.1.15 on 2026-07-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_hierarchical_structure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteElementaire',
        ),
        migrations.AlterUniqueTogether(
            name='elementmodule',
            unique_together={('module', 'code_element')},
        ),
        migrations.AlterUniqueTogether(
            name='resultatsemestre',
            unique_together={('etudiant', 'semestre', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('resultat_semestre', 'code_module')},
        ),
    ]
