# Generated by Django 5.1.15 on 2026-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_hierarchical_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementmodule',
            name='nom_element',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom de l'élément"),
        ),
    ]
