# Generated by Django 5.1.15 on 2026-07-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_computed_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elementmodule',
            unique_together={('resultat_semestre', 'code_element')},
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='nom_matiere',
            field=models.CharField(blank=True, help_text="Nom de l'élément/matière (ex: Frameworks JEE)", max_length=200, verbose_name='Nom de la matière'),
        ),
    ]
